name: Wiki Proposal 📑
description: Suggest an idea for the developersIndia wiki
labels: ["proposal"]
assignees:
  - Bhupesh-V
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea for a wiki proposal 🧡. If you have any questions, join us on Discord
        Make sure to enter a descriptive title above For E.g. "How to navigate interivews in product based companies"
  - type: textarea
    id: description
    attributes:
      label: What's this proposal about? What should this wiki cover? Who's the audience?
      placeholder: The wiki should talk about ...
    validations:
      required: true
  - type: dropdown
    id: is-faq
    attributes:
      label: Is this topic a Frequently Asked Question (FAQ) on r/developersIndia?
      description: We encourage wikis that answer frequently asked questions on the developersIndia subreddit.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: faq-list
    attributes:
      label: If this is a FAQ on the sub, please include links of similar posts from the subreddit
    validations:
      required: false
  - type: dropdown
    id: your-role
    attributes:
      label: Are you interested in authoring this wiki guide?
      description: Being an author makes you responsible for researching every little detail about a wiki once its written & keeping it updated timely.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: read-contrib
    attributes:
      label: Have you read the [contributing guidelines](https://github.com/developersIndia/wiki/blob/main/CONTRIBUTING.md) for propsing a wiki?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/developersIndia/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow the community's Code of Conduct
          required: true
