name: Netlify Deploy

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: 'actions/checkout@v3.0.2'

      - name: Setup mdBook
        uses: extractions/setup-crate@v1
        with:
          owner: rust-lang
          name: mdbook

      - name: Generate the Wiki
        run: mdbook build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        timeout-minutes: 1
